export const LOCAL_PRODUCT_FAMILIES = [
  ["PIPE", "Tubería"],
  ["VALVE", "Válvula"],
  ["FITTING", "Conexión"],
  ["FLANGE", "Brida"],
  ["GROOVED_SYSTEM", "Sistema ranurado"],
  ["SANITARY", "Línea sanitaria"],
  ["INSTRUMENTATION", "Instrumentación y actuación"],
  ["GASKET", "Empaque, junta y sello"],
  ["FASTENER", "Tornillería y sujeción"],
  ["COATING", "Recubrimiento"],
  ["PLATE", "Placa y lámina"],
  ["BAR", "Barra y varilla"],
  ["STRUCTURAL", "Acero estructural"],
  ["COVER_GRATING", "Tapas y rejillas"],
  ["SERVICE", "Servicio de transformación"],
  ["OTHER", "Otro"],
] as const;

export const LOCAL_PRODUCT_SUBFAMILIES: Record<string, ReadonlyArray<readonly [string, string]>> = {
  PIPE: [
    ["CARBON_STEEL_SEAMLESS", "Acero al carbón sin costura"],
    ["CARBON_STEEL_WELDED", "Acero al carbón con costura ERW / HFW"],
    ["LSAW_SAW_PIPE", "Con costura LSAW / SAW"],
    ["SPIRAL_PIPE", "Con costura helicoidal"],
    ["STAINLESS_STEEL_PIPE", "Acero inoxidable"],
    ["ALLOY_STEEL_PIPE", "Acero aleado"],
    ["MECHANICAL_PIPE", "Tubo mecánico"],
    ["STRUCTURAL_PIPE", "Estructural y pilotaje"],
    ["GROOVED_FIRE_PIPE", "Ranurada y contra incendio"],
    ["COATED_PIPE", "Tubería recubierta"],
    ["OCTG_CASING_TUBING", "Casing y tubing"],
    ["DRILL_PIPE", "Tubería de perforación"],
    ["HDPE_PIPE", "Polietileno de alta densidad (HDPE)"],
    ["PVC_CPVC_PIPE", "PVC / CPVC"],
    ["COPPER_PIPE", "Cobre"],
  ],
  VALVE: [
    ["GATE_VALVE", "Compuerta"],
    ["GLOBE_VALVE", "Globo"],
    ["CHECK_VALVE", "Retención / check"],
    ["BALL_VALVE", "Bola"],
    ["BUTTERFLY_VALVE", "Mariposa"],
    ["PLUG_VALVE", "Macho"],
    ["DUO_CHECK_VALVE", "Duo check"],
    ["DIAPHRAGM_VALVE", "Diafragma"],
    ["KNIFE_GATE_VALVE", "Cuchilla"],
    ["PINCH_VALVE", "Pellizco"],
    ["NEEDLE_VALVE", "Aguja"],
    ["SAFETY_RELIEF_VALVE", "Seguridad y alivio"],
    ["CONTROL_REGULATING_VALVE", "Control y regulación"],
    ["GROOVED_VALVE", "Extremos ranurados"],
    ["AIR_VALVE", "Válvula de aire"],
    ["DIVERTER_VALVE", "Desviadora"],
    ["BALANCING_VALVE", "Balanceo hidrónico"],
    ["STRAINER", "Colador / strainer"],
  ],
  FITTING: [
    ["CARBON_STEEL_BUTT_WELD", "Acero al carbón soldable"],
    ["FORGED_STEEL_FITTING", "Acero forjado"],
    ["STAINLESS_STEEL_FITTING", "Acero inoxidable"],
    ["MALLEABLE_IRON_FITTING", "Hierro maleable"],
    ["DUCTILE_IRON_AWWA", "Hierro dúctil / AWWA"],
    ["GROOVED_FITTING", "Conexión ranurada"],
    ["BRANCH_OUTLET", "Olet e injerto"],
    ["THREADED_FITTING", "Conexión roscada"],
    ["SANITARY_FITTING", "Conexión sanitaria"],
    ["PRESS_FITTING", "Conexión press"],
  ],
  FLANGE: [
    ["WELD_NECK_FLANGE", "Cuello soldable"],
    ["SLIP_ON_FLANGE", "Slip-on / deslizable"],
    ["BLIND_FLANGE", "Ciega"],
    ["LAP_JOINT_FLANGE", "Lap joint"],
    ["THREADED_FLANGE", "Roscada"],
    ["SOCKET_WELD_FLANGE", "Socket weld"],
    ["ORIFICE_FLANGE", "Orificio"],
    ["RING_FLANGE", "Anillo"],
  ],
  GROOVED_SYSTEM: [
    ["GROOVED_COUPLING", "Cople ranurado"],
    ["RIGID_COUPLING", "Cople rígido"],
    ["FLEXIBLE_COUPLING", "Cople flexible"],
    ["TRANSITION_COUPLING", "Cople de transición"],
    ["REDUCING_COUPLING", "Cople reductor"],
    ["GROOVED_FITTING_SYSTEM", "Conexión ranurada"],
    ["GROOVED_VALVE_SYSTEM", "Válvula ranurada"],
    ["MECHANICAL_OUTLET", "Derivación mecánica"],
    ["FIRE_PROTECTION", "Protección contra incendio"],
    ["SPRINKLER", "Rociador"],
    ["GROOVING_TOOL", "Herramienta de ranurado"],
    ["GROOVED_ACCESSORY", "Accesorio ranurado"],
    ["FLANGE_ADAPTER", "Adaptador de brida"],
    ["EXPANSION_JOINT", "Junta de expansión"],
    ["PLAIN_END_SYSTEM", "Sistema de extremo liso"],
    ["PRESS_SYSTEM", "Sistema press"],
  ],
  SANITARY: [
    ["SANITARY_PIPE", "Tubería sanitaria"],
    ["SANITARY_FITTING", "Conexión sanitaria"],
    ["SANITARY_VALVE", "Válvula sanitaria"],
    ["SANITARY_CLAMP", "Clamp y abrazadera sanitaria"],
    ["SANITARY_GASKET", "Empaque sanitario"],
  ],
  INSTRUMENTATION: [
    ["ELECTRIC_ACTUATOR", "Actuador eléctrico"],
    ["PNEUMATIC_ACTUATOR", "Actuador neumático"],
    ["HYDRAULIC_ACTUATOR", "Actuador hidráulico"],
    ["GAS_ACTUATOR", "Actuador gas directo / gas sobre aceite"],
    ["ELECTRO_HYDRAULIC_ACTUATOR", "Actuador electrohidráulico"],
    ["POSITIONER", "Posicionador"],
    ["LIMIT_SWITCH", "Interruptor de límite"],
    ["SOLENOID", "Solenoide"],
    ["PRESSURE_INSTRUMENT", "Instrumento de presión"],
    ["FLOW_INSTRUMENT", "Instrumento de flujo"],
    ["TEMPERATURE_INSTRUMENT", "Instrumento de temperatura"],
  ],
  GASKET: [
    ["SPIRAL_WOUND_GASKET", "Junta espirometálica"],
    ["RING_JOINT_GASKET", "Anillo RTJ"],
    ["SHEET_GASKET", "Junta plana / lámina"],
    ["PTFE_GASKET", "Junta PTFE"],
    ["RUBBER_GASKET", "Empaque elastomérico"],
    ["FLANGE_INSULATION_KIT", "Kit de aislamiento de brida"],
    ["MECHANICAL_SEAL", "Sello mecánico"],
  ],
  FASTENER: [
    ["STUD_BOLT", "Espárrago / birlo"],
    ["BOLT", "Tornillo / perno"],
    ["NUT", "Tuerca"],
    ["WASHER", "Arandela"],
    ["ANCHOR", "Ancla"],
    ["PIPE_CLAMP", "Abrazadera y soporte"],
  ],
  COATING: [
    ["FBE_COATING", "FBE"],
    ["THREE_LAYER_PE", "Polietileno tricapa 3LPE"],
    ["THREE_LAYER_PP", "Polipropileno tricapa 3LPP"],
    ["INTERNAL_EPOXY", "Epóxico interior"],
    ["GALVANIZED_COATING", "Galvanizado"],
    ["PAINT_VARNISH", "Pintura y barniz"],
    ["RUBBER_LINING", "Recubrimiento elastomérico"],
  ],
  PLATE: [
    ["CARBON_STEEL_PLATE", "Acero al carbón"],
    ["STAINLESS_STEEL_PLATE", "Acero inoxidable"],
    ["ALLOY_STEEL_PLATE", "Acero aleado"],
    ["GALVANIZED_SHEET", "Lámina galvanizada"],
    ["CHECKERED_PLATE", "Placa antiderrapante"],
  ],
  BAR: [
    ["ROUND_BAR", "Redonda"],
    ["HEX_BAR", "Hexagonal"],
    ["SQUARE_BAR", "Cuadrada"],
    ["FLAT_BAR", "Solera"],
    ["THREADED_ROD", "Roscada"],
  ],
  STRUCTURAL: [
    ["BEAM", "Viga"],
    ["CHANNEL", "Canal"],
    ["ANGLE", "Ángulo"],
    ["HOLLOW_SECTION", "Perfil tubular HSS"],
    ["STRUCTURAL_PROFILE", "Perfil estructural"],
    ["SHEET_PILE", "Tablestaca"],
  ],
  COVER_GRATING: [
    ["MANHOLE_COVER", "Tapa de registro"],
    ["FLOOR_DRAIN", "Coladera"],
    ["INDUSTRIAL_GRATING", "Rejilla industrial"],
    ["TRENCH_GRATE", "Rejilla de zanja"],
  ],
  SERVICE: [
    ["CUTTING_SERVICE", "Corte"],
    ["THREADING_SERVICE", "Roscado"],
    ["GROOVING_SERVICE", "Ranurado"],
    ["BEVELING_SERVICE", "Biselado"],
    ["COATING_SERVICE", "Aplicación de recubrimiento"],
    ["GALVANIZING_SERVICE", "Galvanizado"],
    ["MACHINING_SERVICE", "Maquinado"],
    ["TESTING_CERTIFICATION", "Prueba y certificación"],
  ],
  OTHER: [],
};

export const LOCAL_PRODUCT_TECHNICAL_FIELDS: Record<string, Array<[string, string]>> = {
  PIPE: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["OUTER_DIAMETER", "Diámetro exterior"], ["SCHEDULE", "Cédula"], ["THICKNESS", "Espesor"], ["MANUFACTURING", "Fabricación"], ["END_FINISH", "Extremos"], ["LENGTH", "Longitud"], ["COATING", "Recubrimiento"]],
  VALVE: [["BODY_MATERIAL", "Material del cuerpo"], ["STANDARD", "Norma"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["PRESSURE_CLASS", "Clase / presión"], ["CONNECTION", "Conexión"], ["FACE", "Cara"], ["TRIM", "Trim"], ["BORE", "Paso"], ["OPERATION", "Operación"]],
  FITTING: [["FIGURE", "Figura"], ["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["SCHEDULE", "Cédula / clase"], ["CONNECTION", "Conexión"], ["RADIUS", "Radio"]],
  FLANGE: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["PRESSURE_CLASS", "Clase"], ["FACE", "Cara"], ["SCHEDULE", "Cédula del barreno"]],
  GROOVED_SYSTEM: [["MATERIAL", "Material"], ["STANDARD", "Norma / aprobación"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["PRESSURE_RATING", "Presión nominal"], ["STYLE_SERIES", "Estilo / serie"], ["COATING", "Recubrimiento"]],
  SANITARY: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["WALL_THICKNESS", "Espesor de pared"], ["CONNECTION", "Conexión"], ["SURFACE_FINISH", "Acabado sanitario"], ["GASKET_MATERIAL", "Material del empaque"]],
  INSTRUMENTATION: [["DEVICE_TYPE", "Tipo de dispositivo"], ["POWER_SOURCE", "Fuente de energía"], ["TORQUE", "Torque"], ["VOLTAGE", "Voltaje"], ["SIGNAL", "Señal"], ["ENCLOSURE", "Protección / gabinete"], ["FAIL_POSITION", "Posición de falla"], ["CERTIFICATION", "Certificación"]],
  GASKET: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["NOMINAL_DIAMETER", "Diámetro nominal"], ["PRESSURE_CLASS", "Clase"], ["THICKNESS", "Espesor"], ["FILLER", "Relleno"], ["INNER_RING", "Anillo interior"], ["OUTER_RING", "Anillo exterior"]],
  FASTENER: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["DIAMETER", "Diámetro"], ["THREAD", "Rosca"], ["LENGTH", "Longitud"], ["COATING", "Recubrimiento"]],
  COATING: [["COATING_SYSTEM", "Sistema"], ["STANDARD", "Norma"], ["THICKNESS", "Espesor"], ["COLOR", "Color"], ["SERVICE_TEMPERATURE", "Temperatura de servicio"], ["APPLICATION", "Aplicación"]],
  PLATE: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["THICKNESS", "Espesor"], ["WIDTH", "Ancho"], ["LENGTH", "Largo"], ["FINISH", "Acabado"]],
  BAR: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["DIAMETER", "Diámetro / sección"], ["LENGTH", "Longitud"], ["FINISH", "Acabado"]],
  STRUCTURAL: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["GRADE", "Grado"], ["SECTION", "Sección / perfil"], ["THICKNESS", "Espesor"], ["LENGTH", "Longitud"], ["WEIGHT", "Peso por metro"]],
  COVER_GRATING: [["MATERIAL", "Material"], ["STANDARD", "Norma"], ["LOAD_CLASS", "Clase de carga"], ["WIDTH", "Ancho"], ["LENGTH", "Largo"], ["HEIGHT", "Altura"], ["COATING", "Recubrimiento"]],
  SERVICE: [["BASE_MATERIAL", "Material base"], ["STANDARD", "Norma requerida"], ["DIMENSIONS", "Dimensiones"], ["FINISH", "Acabado"], ["CERTIFICATION", "Certificación"], ["SCOPE", "Alcance del servicio"]],
  OTHER: [],
};

export const getLocalProductFamilyLabel = (family: string | null | undefined): string =>
  LOCAL_PRODUCT_FAMILIES.find(([value]) => value === family)?.[1] || family || "Por definir";

export const getLocalProductSubfamilyLabel = (
  family: string | null | undefined,
  subfamily: string | null | undefined,
): string =>
  (family ? LOCAL_PRODUCT_SUBFAMILIES[family] : undefined)?.find(([value]) => value === subfamily)?.[1]
  || subfamily
  || "Por definir";

export const LOCAL_PRODUCT_COST_SOURCE_OPTIONS = [
  ["MANUAL_ESTIMATE", "Estimación manual"],
  ["PRICE_LIST", "Lista de precios"],
] as const;
